import { HttpError, randomId, stableJson, toCents, toMilli } from "../runtime";
import { extractTable } from "./supabase";
import type { MigrationContext, MigrationDomain, SourceRow, WriteUnit } from "./types";

export type TaggedRow = SourceRow & { __source_table: string };
export const text=(value:unknown,fallback=""):string=>{const result=String(value??"").trim();return result||fallback;};
export const nullable=(value:unknown):string|null=>text(value)||null;
export const boolInt=(value:unknown,fallback=true):number=>{if(value===null||value===undefined)return fallback?1:0;if(typeof value==="boolean")return value?1:0;return["true","1","yes","sim","active","ativo"].includes(text(value).toLowerCase())?1:0;};
export const jsonObject=(value:unknown):Record<string,unknown>=>{if(value&&typeof value==="object"&&!Array.isArray(value))return value as Record<string,unknown>;if(typeof value==="string"){try{const parsed=JSON.parse(value);return parsed&&typeof parsed==="object"&&!Array.isArray(parsed)?parsed:{};}catch{return{};}}return{};};
export const jsonArray=(value:unknown):unknown[]=>{if(Array.isArray(value))return value;if(typeof value==="string"){try{const parsed=JSON.parse(value);return Array.isArray(parsed)?parsed:[];}catch{return[];}}return[];};
export const sourceId=(row:TaggedRow):string=>{const id=text(row.id);if(!id)throw new HttpError(422,"SOURCE_ID_REQUIRED",`${row.__source_table} row has no stable id`);return`${row.__source_table}:${id}`;};
export const targetId=(row:SourceRow,prefix:string):string=>{const id=text(row.id);if(!id)throw new HttpError(422,"SOURCE_ID_REQUIRED",`${prefix} source row has no stable id`);return id;};
export const normalizeSpecies=(value:unknown):string=>{const v=text(value,"other").toLowerCase();if(["dog","cachorro","cao","cão","canino"].includes(v))return"dog";if(["cat","gato","gata","felino"].includes(v))return"cat";if(["bird","passaro","pássaro","ave"].includes(v))return"bird";if(["rabbit","coelho"].includes(v))return"rabbit";if(["fish","peixe"].includes(v))return"fish";return"other";};

export const DEFAULT_MODULE_PERMISSIONS=["clients:read","clients:write","catalog:read","catalog:write","appointments:read","appointments:write","sales:read","sales:write","settings:read","settings:write"];
export const normalizePermissionList=(value:unknown,role:string):string[]=>{if(role==="admin")return["*"];if(Array.isArray(value))return[...new Set(value.map(String).filter(Boolean))];const object=jsonObject(value);const explicit=Object.entries(object).filter(([,allowed])=>allowed===true||allowed===1||allowed==="true").map(([permission])=>permission);return explicit.length?[...new Set(explicit)]:DEFAULT_MODULE_PERMISSIONS;};
export const normalizeTransport=(value:unknown):"none"|"pickup"|"dropoff"|"roundtrip"=>{const v=text(value).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");if(["roundtrip","buscar_e_levar","buscar e levar","buscar_e_trazer","buscar e trazer","both"].includes(v))return"roundtrip";if(["pickup","buscar","so_buscar","apenas_buscar"].includes(v))return"pickup";if(["dropoff","levar","so_levar","apenas_levar"].includes(v))return"dropoff";return"none";};
export async function tagged(context:MigrationContext,table:string,options:Parameters<typeof extractTable>[2]={}):Promise<TaggedRow[]>{const rows=await extractTable(context,table,{...options,optional:true});return rows.map((row)=>({...row,__source_table:table}));}
export async function taggedChildren(context:MigrationContext,table:string,parentColumn:string,parentIds:string[]):Promise<TaggedRow[]>{const unique=[...new Set(parentIds.filter(Boolean))],out:TaggedRow[]=[];for(let i=0;i<unique.length;i+=100){const chunk=unique.slice(i,i+100);const rows=await extractTable(context,table,{tenantScoped:false,moduleScoped:false,optional:true,extra:{[parentColumn]:`in.(${chunk.join(",")})`}});out.push(...rows.map((row)=>({...row,__source_table:table})));}return out;}
export function unit(context:MigrationContext,row:TaggedRow,table:string,id:string,statement:D1PreparedStatement,fingerprint:Record<string,unknown>):WriteUnit{return{table,sourceSystem:"supabase",sourceId:sourceId(row),targetId:id,statement,fingerprint};}
export async function resolveMappedTarget(context:MigrationContext,domain:MigrationDomain,sourceTable:string,legacyId:unknown,targetTable:string):Promise<string|null>{const id=text(legacyId);if(!id)return null;const row=await context.env.DB.prepare(`SELECT target_id FROM migration_identity_map WHERE tenant_id=? AND module_id=? AND domain=? AND source_system='supabase' AND source_id=? AND target_table=? LIMIT 1`).bind(context.scope.tenantId,context.scope.moduleId,domain,`${sourceTable}:${id}`,targetTable).first<{target_id:string}>();return row?.target_id??null;}
export async function mappedFingerprint(context:MigrationContext,domain:MigrationDomain){const result=await context.env.DB.prepare(`SELECT source_id,target_table,target_id,normalized_fingerprint FROM migration_identity_map WHERE tenant_id=? AND module_id=? AND domain=? AND migration_version=? ORDER BY source_id,target_table,target_id`).bind(context.scope.tenantId,context.scope.moduleId,domain,context.scope.migrationVersion).all<{source_id:string;target_table:string;target_id:string;normalized_fingerprint:string}>();const rows=result.results??[];return{fingerprint:stableJson(rows),metrics:{mappedRows:rows.length}};}
export{randomId,stableJson,toCents,toMilli};
