import type { DomainMigration } from "./types";
import { boolInt, jsonArray, jsonObject, mappedFingerprint, normalizeTransport, nullable, resolveMappedTarget, stableJson, tagged, targetId, text, toCents, toMilli, unit, type TaggedRow } from "./common";

export const operationalConfig: DomainMigration={
  domain:"operational_config",dependencies:[],
  async extract(context){return await tagged(context,"settings");},
  async normalize(raw,context){const row=raw as TaggedRow;const t=context.scope.tenantId,m=context.scope.moduleId;const id=`${t}:${m}`;const fp={tenant_id:t,module_id:m,store_name:nullable(row.store_name),store_address:nullable(row.store_address),store_neighborhood:nullable(row.store_neighborhood),store_city:nullable(row.store_city),store_phone:nullable(row.store_phone),timezone:text(row.timezone,"America/Sao_Paulo"),printer_width:Number(row.printer_width??80)||80,max_pdv_discount_basis_points:Math.round(Number(row.max_pdv_discount_percent??10)*100),autonomy_policy_json:stableJson(jsonObject(row.autonomy_policy ?? row.bot_autonomy)),metadata_json:stableJson(jsonObject(row))};return[unit(context,row,"operational_configs",id,context.env.DB.prepare(`INSERT INTO operational_configs(tenant_id,module_id,store_name,store_address,store_neighborhood,store_city,store_phone,timezone,printer_width,max_pdv_discount_basis_points,autonomy_policy_json,metadata_json,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(tenant_id,module_id) DO UPDATE SET store_name=excluded.store_name,store_address=excluded.store_address,store_neighborhood=excluded.store_neighborhood,store_city=excluded.store_city,store_phone=excluded.store_phone,timezone=excluded.timezone,printer_width=excluded.printer_width,max_pdv_discount_basis_points=excluded.max_pdv_discount_basis_points,autonomy_policy_json=excluded.autonomy_policy_json,metadata_json=excluded.metadata_json,updated_at=CURRENT_TIMESTAMP`).bind(t,m,fp.store_name,fp.store_address,fp.store_neighborhood,fp.store_city,fp.store_phone,fp.timezone,fp.printer_width,fp.max_pdv_discount_basis_points,fp.autonomy_policy_json,fp.metadata_json),fp)];},targetFingerprint:(context)=>mappedFingerprint(context,"operational_config")
};

export const appointments: DomainMigration={
  domain:"appointments",dependencies:["clients_pets","catalog"],
  async extract(context){return await tagged(context,"appointments");},
  async normalize(raw,context){
    const row=raw as TaggedRow,t=context.scope.tenantId,m=context.scope.moduleId,id=targetId(row,"appointment");
    const legacyClientId=text(row.client_id??row.pet_id),legacyPetId=text(row.pet_id??row.client_id);
    if(!legacyClientId||!legacyPetId)return[];
    const clientId=(await resolveMappedTarget(context,"clients_pets","clients",legacyClientId,"clients"))??legacyClientId;
    const petId=(await resolveMappedTarget(context,"clients_pets","clients",legacyPetId,"pets"))??legacyPetId;
    const fp={id,tenant_id:t,module_id:m,client_id:clientId,pet_id:petId,scheduled_at:text(row.scheduled_at),duration_minutes:Math.max(1,Number(row.duration_min??60)),status:text(row.status,"scheduled"),live_status:nullable(row.live_status),source:nullable(row.source),notes:nullable(row.notes),employee_id:nullable(row.employee_id),groomer_id:nullable(row.groomer_id),responsible_staff_key:nullable(row.responsible_staff_key),responsible_staff_name:nullable(row.responsible_staff_name),subscription_id:nullable(row.subscription_id),subscription_benefit_used:boolInt(row.subscription_benefit_used,false),idempotency_key:nullable(row.idempotency_key)};
    const units=[unit(context,row,"appointments",id,context.env.DB.prepare(`INSERT INTO appointments(id,tenant_id,module_id,client_id,pet_id,scheduled_at,duration_minutes,status,live_status,source,notes,employee_id,groomer_id,responsible_staff_key,responsible_staff_name,subscription_id,subscription_benefit_used,idempotency_key,source_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET client_id=excluded.client_id,pet_id=excluded.pet_id,scheduled_at=excluded.scheduled_at,duration_minutes=excluded.duration_minutes,status=excluded.status,live_status=excluded.live_status,source=excluded.source,notes=excluded.notes,employee_id=excluded.employee_id,groomer_id=excluded.groomer_id,responsible_staff_key=excluded.responsible_staff_key,responsible_staff_name=excluded.responsible_staff_name,subscription_id=excluded.subscription_id,subscription_benefit_used=excluded.subscription_benefit_used,idempotency_key=excluded.idempotency_key,updated_at=CURRENT_TIMESTAMP`).bind(id,t,m,clientId,petId,fp.scheduled_at,fp.duration_minutes,fp.status,fp.live_status,fp.source,fp.notes,fp.employee_id,fp.groomer_id,fp.responsible_staff_key,fp.responsible_staff_name,fp.subscription_id,fp.subscription_benefit_used,fp.idempotency_key,text(row.id),nullable(row.created_at)),fp)];
    const items=jsonArray(row.service_items);const normalizedItems=items.length?items:[{service_type:row.service_type,name:row.service_type,price:row.price,duration_min:row.duration_min}];
    for(let index=0;index<normalizedItems.length;index+=1){const x=jsonObject(normalizedItems[index]);const legacyServiceId=text(x.service_id??x.id);const serviceId=legacyServiceId?(await resolveMappedTarget(context,"catalog","petshop_services",legacyServiceId,"services")):null;const serviceCode=text(x.service_code??x.service_type??row.service_type,"legacy-service");const serviceName=text(x.name??x.label??x.service_type??row.service_type,"Serviço");const sid=`${id}:service:${index}`;const sfp={id:sid,tenant_id:t,module_id:m,appointment_id:id,service_id:serviceId,service_code_snapshot:serviceCode,service_name_snapshot:serviceName,price_cents_snapshot:toCents(x.price??row.price),duration_minutes_snapshot:Math.max(1,Number(x.duration_min??row.duration_min??60)),quantity_milli:toMilli(x.quantity??1)};units.push(unit(context,{...row,__source_table:`${row.__source_table}.service.${index}`} as TaggedRow,"appointment_services",sid,context.env.DB.prepare(`INSERT INTO appointment_services(id,tenant_id,module_id,appointment_id,service_id,service_code_snapshot,service_name_snapshot,price_cents_snapshot,duration_minutes_snapshot,quantity_milli) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET service_id=excluded.service_id,service_code_snapshot=excluded.service_code_snapshot,service_name_snapshot=excluded.service_name_snapshot,price_cents_snapshot=excluded.price_cents_snapshot,duration_minutes_snapshot=excluded.duration_minutes_snapshot,quantity_milli=excluded.quantity_milli`).bind(sid,t,m,id,serviceId,serviceCode,serviceName,sfp.price_cents_snapshot,sfp.duration_minutes_snapshot,sfp.quantity_milli),sfp));}
    return units;
  },targetFingerprint:(context)=>mappedFingerprint(context,"appointments")
};

export const motodog:DomainMigration={domain:"motodog",dependencies:["appointments"],async extract(context){return await tagged(context,"appointments",{extra:{transport_mode:"not.is.null"}});},async normalize(raw,context){const row=raw as TaggedRow,t=context.scope.tenantId,m=context.scope.moduleId,appointmentId=text(row.id);if(!appointmentId)return[];const mode=normalizeTransport(row.transport_mode);if(mode==="none")return[];const id=`motodog:${appointmentId}`;const city=text(row.transport_city).toLowerCase();const fp={id,tenant_id:t,module_id:m,appointment_id:appointmentId,mode,outside_muriae:city&&!city.includes("muria")?1:0,pet_weight_grams:row.weight_kg==null?null:Math.round(Number(row.weight_kg)*1000),fee_cents:toCents(row.transport_fee??row.delivery_fee),address:nullable(row.transport_address),neighborhood:nullable(row.transport_neighborhood),city:nullable(row.transport_city),reference:nullable(row.transport_reference),delivery_staff_key:nullable(row.delivery_staff_key),delivery_staff_name:nullable(row.delivery_staff_name)};return[unit(context,row,"motodog_options",id,context.env.DB.prepare(`INSERT INTO motodog_options(id,tenant_id,module_id,appointment_id,mode,outside_muriae,pet_weight_grams,fee_cents,address,neighborhood,city,reference,delivery_staff_key,delivery_staff_name,source_id,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(tenant_id,module_id,appointment_id) DO UPDATE SET mode=excluded.mode,outside_muriae=excluded.outside_muriae,pet_weight_grams=excluded.pet_weight_grams,fee_cents=excluded.fee_cents,address=excluded.address,neighborhood=excluded.neighborhood,city=excluded.city,reference=excluded.reference,delivery_staff_key=excluded.delivery_staff_key,delivery_staff_name=excluded.delivery_staff_name,updated_at=CURRENT_TIMESTAMP`).bind(id,t,m,appointmentId,mode,fp.outside_muriae,fp.pet_weight_grams,fp.fee_cents,fp.address,fp.neighborhood,fp.city,fp.reference,fp.delivery_staff_key,fp.delivery_staff_name,text(row.id)),fp)];},targetFingerprint:(context)=>mappedFingerprint(context,"motodog")};
