import { requirePermission, type AuthContext } from "../auth";
import { HttpError, header, json, randomId, stableJson, toCents, toMilli, type RuntimeEnv } from "../runtime";
import { asText, boolInt, limitFrom, productDto, readBody, serviceDto } from "./common";

async function product(env:RuntimeEnv,auth:AuthContext,id:string){return env.DB.prepare(`SELECT p.*,COALESCE(b.quantity_milli,0) quantity_milli FROM products p LEFT JOIN inventory_balances b ON b.tenant_id=p.tenant_id AND b.module_id=p.module_id AND b.product_id=p.id WHERE p.id=? AND p.tenant_id=? AND p.module_id=? LIMIT 1`).bind(id,auth.tenantId,auth.moduleId).first<Record<string,unknown>>();}
async function service(env:RuntimeEnv,auth:AuthContext,id:string){return env.DB.prepare(`SELECT * FROM services WHERE id=? AND tenant_id=? AND module_id=? LIMIT 1`).bind(id,auth.tenantId,auth.moduleId).first<Record<string,unknown>>();}

export async function handleProducts(request:Request,env:RuntimeEnv,auth:AuthContext,id?:string):Promise<Response>{
  if(request.method==='GET'){requirePermission(auth,'catalog:read');if(id){const row=await product(env,auth,id);if(!row)throw new HttpError(404,'NOT_FOUND','Resource not found');return json({data:productDto(row)});}const url=new URL(request.url),search=(url.searchParams.get('search')??'').trim(),category=(url.searchParams.get('category')??'').trim(),limit=limitFrom(request);let sql=`SELECT p.*,COALESCE(b.quantity_milli,0) quantity_milli FROM products p LEFT JOIN inventory_balances b ON b.tenant_id=p.tenant_id AND b.module_id=p.module_id AND b.product_id=p.id WHERE p.tenant_id=? AND p.module_id=? AND p.active=1`,bind:unknown[]=[auth.tenantId,auth.moduleId];if(search){sql+=` AND p.name LIKE ?`;bind.push(`%${search}%`);}if(category){sql+=` AND p.category=?`;bind.push(category);}sql+=` ORDER BY p.name LIMIT ?`;bind.push(limit);const rows=await env.DB.prepare(sql).bind(...bind).all<Record<string,unknown>>();return json({data:(rows.results??[]).map(productDto)});}
  if(request.method==='POST'){requirePermission(auth,'catalog:write');const body=await readBody(request),name=asText(body.name);if(!name)throw new HttpError(400,'PRODUCT_NAME_REQUIRED','Product name is required');const id=asText(body.id)??randomId('product'),initial=toMilli(body.stockQuantity??0),now=new Date().toISOString(),metadata=stableJson(body.metadata??{});const statements:D1PreparedStatement[]=[env.DB.prepare(`INSERT INTO products(id,tenant_id,module_id,name,barcode,category,description,price_cents,cost_cents,min_quantity_milli,species_target,image_url,active,metadata_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,auth.tenantId,auth.moduleId,name,asText(body.barcode),asText(body.category),asText(body.description),toCents(body.price),toCents(body.costPrice),toMilli(body.minStock),asText(body.speciesTarget),asText(body.imageUrl),boolInt(body.active,true),metadata,now,now),env.DB.prepare(`INSERT INTO inventory_balances(tenant_id,module_id,product_id,quantity_milli,version,updated_at) VALUES(?,?,?,?,1,?)`).bind(auth.tenantId,auth.moduleId,id,initial,now)];if(initial!==0){statements.push(env.DB.prepare(`INSERT INTO inventory_movements(id,tenant_id,module_id,product_id,movement_type,quantity_milli,balance_before_milli,balance_after_milli,reason,idempotency_key,occurred_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).bind(randomId('inventory'),auth.tenantId,auth.moduleId,id,'opening',initial,0,initial,'Initial stock',`product-create:${id}`,now,now));}await env.DB.batch(statements);return json({data:productDto((await product(env,auth,id))!)},201);}
  if(request.method==='PATCH'&&id){requirePermission(auth,'catalog:write');const current=await product(env,auth,id);if(!current)throw new HttpError(404,'NOT_FOUND','Resource not found');const body=await readBody(request),pick=(key:string,currentKey=key)=>Object.prototype.hasOwnProperty.call(body,key)?body[key]:current[currentKey];await env.DB.prepare(`UPDATE products SET name=?,barcode=?,category=?,description=?,price_cents=?,cost_cents=?,min_quantity_milli=?,species_target=?,image_url=?,active=?,metadata_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=? AND module_id=?`).bind(asText(pick('name'))??String(current.name),asText(pick('barcode')),asText(pick('category')),asText(pick('description')),Object.prototype.hasOwnProperty.call(body,'price')?toCents(body.price):Number(current.price_cents),Object.prototype.hasOwnProperty.call(body,'costPrice')?toCents(body.costPrice):Number(current.cost_cents),Object.prototype.hasOwnProperty.call(body,'minStock')?toMilli(body.minStock):Number(current.min_quantity_milli),asText(pick('speciesTarget','species_target')),asText(pick('imageUrl','image_url')),Object.prototype.hasOwnProperty.call(body,'active')?boolInt(body.active,true):Number(current.active),Object.prototype.hasOwnProperty.call(body,'metadata')?stableJson(body.metadata??{}):String(current.metadata_json??'{}'),id,auth.tenantId,auth.moduleId).run();
    if(Object.prototype.hasOwnProperty.call(body,'stockQuantity')){const key=header(request,'x-idempotency-key');if(!key)throw new HttpError(400,'IDEMPOTENCY_KEY_REQUIRED','x-idempotency-key is required for stock changes');const existing=await env.DB.prepare(`SELECT id FROM inventory_movements WHERE tenant_id=? AND module_id=? AND idempotency_key=? LIMIT 1`).bind(auth.tenantId,auth.moduleId,key).first();if(!existing){const before=Number(current.quantity_milli??0),after=toMilli(body.stockQuantity),delta=after-before;if(delta!==0){await env.DB.batch([env.DB.prepare(`INSERT INTO inventory_movements(id,tenant_id,module_id,product_id,movement_type,quantity_milli,balance_before_milli,balance_after_milli,reason,idempotency_key,occurred_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(randomId('inventory'),auth.tenantId,auth.moduleId,id,'adjustment',delta,before,after,asText(body.stockReason)??'Manual adjustment',key),env.DB.prepare(`INSERT INTO inventory_balances(tenant_id,module_id,product_id,quantity_milli,version,updated_at) VALUES(?,?,?,?,1,CURRENT_TIMESTAMP) ON CONFLICT(tenant_id,module_id,product_id) DO UPDATE SET quantity_milli=excluded.quantity_milli,version=inventory_balances.version+1,updated_at=CURRENT_TIMESTAMP`).bind(auth.tenantId,auth.moduleId,id,after)]);}}}
    return json({data:productDto((await product(env,auth,id))!)});
  }
  if(request.method==='DELETE'&&id){requirePermission(auth,'catalog:write');const current=await product(env,auth,id);if(!current)throw new HttpError(404,'NOT_FOUND','Resource not found');await env.DB.prepare(`UPDATE products SET active=0,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=? AND module_id=?`).bind(id,auth.tenantId,auth.moduleId).run();return json({data:{ok:true}});}
  throw new HttpError(405,'METHOD_NOT_ALLOWED','Method not allowed');
}

export async function handleServices(request:Request,env:RuntimeEnv,auth:AuthContext,id?:string):Promise<Response>{
  if(request.method==='GET'){requirePermission(auth,'catalog:read');if(id){const row=await service(env,auth,id);if(!row)throw new HttpError(404,'NOT_FOUND','Resource not found');return json({data:serviceDto(row)});}const rows=await env.DB.prepare(`SELECT * FROM services WHERE tenant_id=? AND module_id=? AND active=1 ORDER BY name LIMIT ?`).bind(auth.tenantId,auth.moduleId,limitFrom(request)).all<Record<string,unknown>>();return json({data:(rows.results??[]).map(serviceDto)});}
  if(request.method==='POST'){requirePermission(auth,'catalog:write');const body=await readBody(request),name=asText(body.name),code=asText(body.code);if(!name||!code)throw new HttpError(400,'SERVICE_FIELDS_REQUIRED','Service name and code are required');const id=asText(body.id)??randomId('service');await env.DB.prepare(`INSERT INTO services(id,tenant_id,module_id,code,name,service_group,description,price_cents,duration_minutes,species_rule,commission_basis_points,active,metadata_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(id,auth.tenantId,auth.moduleId,code,name,asText(body.group)??'other',asText(body.description),toCents(body.price),Math.max(1,Number(body.durationMinutes??60)),asText(body.speciesRule)??'all',body.commissionPercent==null?null:Math.round(Number(body.commissionPercent)*100),boolInt(body.active,true),stableJson(body.metadata??{})).run();return json({data:serviceDto((await service(env,auth,id))!)},201);}
  if(request.method==='PATCH'&&id){requirePermission(auth,'catalog:write');const current=await service(env,auth,id);if(!current)throw new HttpError(404,'NOT_FOUND','Resource not found');const body=await readBody(request);const get=(k:string,c=k)=>Object.prototype.hasOwnProperty.call(body,k)?body[k]:current[c];await env.DB.prepare(`UPDATE services SET code=?,name=?,service_group=?,description=?,price_cents=?,duration_minutes=?,species_rule=?,commission_basis_points=?,active=?,metadata_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=? AND module_id=?`).bind(asText(get('code'))??String(current.code),asText(get('name'))??String(current.name),asText(get('group','service_group'))??'other',asText(get('description')),Object.prototype.hasOwnProperty.call(body,'price')?toCents(body.price):Number(current.price_cents),Object.prototype.hasOwnProperty.call(body,'durationMinutes')?Math.max(1,Number(body.durationMinutes)):Number(current.duration_minutes),asText(get('speciesRule','species_rule'))??'all',Object.prototype.hasOwnProperty.call(body,'commissionPercent')?(body.commissionPercent==null?null:Math.round(Number(body.commissionPercent)*100)):current.commission_basis_points,Object.prototype.hasOwnProperty.call(body,'active')?boolInt(body.active,true):Number(current.active),Object.prototype.hasOwnProperty.call(body,'metadata')?stableJson(body.metadata??{}):String(current.metadata_json??'{}'),id,auth.tenantId,auth.moduleId).run();return json({data:serviceDto((await service(env,auth,id))!)});}
  if(request.method==='DELETE'&&id){requirePermission(auth,'catalog:write');await env.DB.prepare(`UPDATE services SET active=0,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=? AND module_id=?`).bind(id,auth.tenantId,auth.moduleId).run();return json({data:{ok:true}});}
  throw new HttpError(405,'METHOD_NOT_ALLOWED','Method not allowed');
}
