import { requirePermission, type AuthContext } from "../auth";
import { HttpError, header, json, randomId, toCents, toMilli, type RuntimeEnv } from "../runtime";
import { asText, limitFrom, readBody } from "./common";

type Row=Record<string,unknown>;
async function sale(env:RuntimeEnv,auth:AuthContext,id:string){return env.DB.prepare(`SELECT * FROM sales WHERE id=? AND tenant_id=? AND module_id=? LIMIT 1`).bind(id,auth.tenantId,auth.moduleId).first<Row>();}
async function saleDto(env:RuntimeEnv,auth:AuthContext,row:Row){const items=await env.DB.prepare(`SELECT * FROM sale_items WHERE sale_id=? AND tenant_id=? AND module_id=? ORDER BY created_at,id`).bind(String(row.id),auth.tenantId,auth.moduleId).all<Row>();const payments=await env.DB.prepare(`SELECT * FROM payments WHERE sale_id=? AND tenant_id=? AND module_id=? ORDER BY created_at,id`).bind(String(row.id),auth.tenantId,auth.moduleId).all<Row>();const paymentData=[];for(const p of payments.results??[]){const splits=await env.DB.prepare(`SELECT id,method,amount_cents,external_reference FROM payment_splits WHERE payment_id=? AND tenant_id=? AND module_id=? ORDER BY created_at,id`).bind(String(p.id),auth.tenantId,auth.moduleId).all<Row>();paymentData.push({id:p.id,method:p.method,amount:Number(p.amount_cents??0)/100,status:p.status,externalReference:p.external_reference,paidAt:p.paid_at,splits:(splits.results??[]).map(s=>({id:s.id,method:s.method,amount:Number(s.amount_cents??0)/100,externalReference:s.external_reference}))});}return{id:row.id,clientId:row.client_id,customerName:row.customer_name,customerPhone:row.customer_phone,subtotal:Number(row.subtotal_cents??0)/100,discount:Number(row.discount_cents??0)/100,total:Number(row.total_cents??0)/100,status:row.status,source:row.source,fulfillmentType:row.fulfillment_type,notes:row.notes,createdAt:row.created_at,items:(items.results??[]).map(i=>({id:i.id,kind:i.item_kind,productId:i.product_id,serviceId:i.service_id,description:i.description_snapshot,quantity:Number(i.quantity_milli??0)/1000,unitPrice:Number(i.unit_price_cents??0)/100,subtotal:Number(i.subtotal_cents??0)/100,upsell:i.upsell===1})),payments:paymentData};}

export async function handleSales(request:Request,env:RuntimeEnv,auth:AuthContext,id?:string):Promise<Response>{
  if(request.method==='GET'){requirePermission(auth,'sales:read');if(id){const row=await sale(env,auth,id);if(!row)throw new HttpError(404,'NOT_FOUND','Resource not found');return json({data:await saleDto(env,auth,row)});}const rows=await env.DB.prepare(`SELECT * FROM sales WHERE tenant_id=? AND module_id=? ORDER BY created_at DESC LIMIT ?`).bind(auth.tenantId,auth.moduleId,limitFrom(request)).all<Row>();return json({data:(rows.results??[]).map(r=>({id:r.id,clientId:r.client_id,customerName:r.customer_name,total:Number(r.total_cents??0)/100,status:r.status,source:r.source,createdAt:r.created_at}))});}
  if(request.method==='POST'){
    requirePermission(auth,'sales:write');const key=header(request,'x-idempotency-key');if(!key)throw new HttpError(400,'IDEMPOTENCY_KEY_REQUIRED','x-idempotency-key is required');const replay=await env.DB.prepare(`SELECT id FROM sales WHERE tenant_id=? AND module_id=? AND idempotency_key=? LIMIT 1`).bind(auth.tenantId,auth.moduleId,key).first<{id:string}>();if(replay){const row=await sale(env,auth,replay.id);return json({data:await saleDto(env,auth,row!),idempotentReplay:true});}
    const body=await readBody(request),rawItems=Array.isArray(body.items)?body.items:[];if(!rawItems.length)throw new HttpError(400,'SALE_ITEMS_REQUIRED','At least one sale item is required');const saleId=asText(body.id)??randomId('sale');const normalized=[] as Array<{id:string;kind:'product'|'service';productId:string|null;serviceId:string|null;description:string;quantityMilli:number;unitPriceCents:number;subtotalCents:number;upsell:number}>;let subtotal=0;
    for(let index=0;index<rawItems.length;index+=1){const item=(rawItems[index]??{}) as Row;const productId=asText(item.productId),serviceId=asText(item.serviceId),kind: 'product'|'service'=serviceId?'service':'product';if(kind==='product'&&!productId)throw new HttpError(400,'PRODUCT_ID_REQUIRED','Product item requires productId');let source:Row|null=null;if(productId)source=await env.DB.prepare(`SELECT id,name,price_cents FROM products WHERE id=? AND tenant_id=? AND module_id=? AND active=1 LIMIT 1`).bind(productId,auth.tenantId,auth.moduleId).first<Row>();if(serviceId)source=await env.DB.prepare(`SELECT id,name,price_cents FROM services WHERE id=? AND tenant_id=? AND module_id=? AND active=1 LIMIT 1`).bind(serviceId,auth.tenantId,auth.moduleId).first<Row>();if(!source)throw new HttpError(404,'SALE_ITEM_NOT_FOUND','Sale item not found');const quantityMilli=toMilli(item.quantity??1);if(quantityMilli<=0)throw new HttpError(400,'INVALID_QUANTITY','Quantity must be positive');const unitPriceCents=Object.prototype.hasOwnProperty.call(item,'unitPrice')?toCents(item.unitPrice):Number(source.price_cents??0);const subtotalCents=Math.round(unitPriceCents*quantityMilli/1000);subtotal+=subtotalCents;normalized.push({id:`${saleId}:item:${index}`,kind,productId:productId??null,serviceId:serviceId??null,description:asText(item.description)??String(source.name),quantityMilli,unitPriceCents,subtotalCents,upsell:item.upsell?1:0});}
    const discount=Math.max(0,toCents(body.discount??0)),total=Math.max(0,subtotal-discount);const statements:D1PreparedStatement[]=[env.DB.prepare(`INSERT INTO sales(id,tenant_id,module_id,client_id,profile_id,customer_name,customer_phone,source,fulfillment_type,subtotal_cents,discount_cents,total_cents,status,notes,idempotency_key,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)`).bind(saleId,auth.tenantId,auth.moduleId,asText(body.clientId),auth.userId,asText(body.customerName),asText(body.customerPhone),asText(body.source)??'pdv',asText(body.fulfillmentType)??'counter',subtotal,discount,total,asText(body.status)??'completed',asText(body.notes),key,new Date().toISOString())];
    for(const item of normalized){statements.push(env.DB.prepare(`INSERT INTO sale_items(id,tenant_id,module_id,sale_id,item_kind,product_id,service_id,description_snapshot,quantity_milli,unit_price_cents,subtotal_cents,upsell) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).bind(item.id,auth.tenantId,auth.moduleId,saleId,item.kind,item.productId,item.serviceId,item.description,item.quantityMilli,item.unitPriceCents,item.subtotalCents,item.upsell));if(item.productId){const balance=await env.DB.prepare(`SELECT quantity_milli FROM inventory_balances WHERE tenant_id=? AND module_id=? AND product_id=? LIMIT 1`).bind(auth.tenantId,auth.moduleId,item.productId).first<{quantity_milli:number}>();const before=Number(balance?.quantity_milli??0),after=before-item.quantityMilli;if(after<0)throw new HttpError(409,'INSUFFICIENT_STOCK',`Insufficient stock for ${item.description}`);const movementKey=`${key}:inventory:${item.productId}:${item.id}`;statements.push(env.DB.prepare(`UPDATE inventory_balances SET quantity_milli=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND module_id=? AND product_id=?`).bind(after,auth.tenantId,auth.moduleId,item.productId));statements.push(env.DB.prepare(`INSERT INTO inventory_movements(id,tenant_id,module_id,product_id,movement_type,quantity_milli,balance_before_milli,balance_after_milli,reference_type,reference_id,reason,idempotency_key,occurred_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(randomId('inventory'),auth.tenantId,auth.moduleId,item.productId,'sale',-item.quantityMilli,before,after,'sale',saleId,'Sale checkout',movementKey));}}
    const rawPayment=(body.payment??null) as Row|null;if(rawPayment){const paymentId=randomId('payment'),amount=Object.prototype.hasOwnProperty.call(rawPayment,'amount')?toCents(rawPayment.amount):total;if(amount<=0)throw new HttpError(400,'INVALID_PAYMENT_AMOUNT','Payment amount must be positive');statements.push(env.DB.prepare(`INSERT INTO payments(id,tenant_id,module_id,sale_id,method,amount_cents,status,external_reference,idempotency_key,paid_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)`).bind(paymentId,auth.tenantId,auth.moduleId,saleId,asText(rawPayment.method)??'unknown',amount,asText(rawPayment.status)??'paid',asText(rawPayment.externalReference),`${key}:payment`,asText(rawPayment.paidAt)??new Date().toISOString()));const splits=Array.isArray(rawPayment.splits)?rawPayment.splits:[];for(let i=0;i<splits.length;i+=1){const split=(splits[i]??{}) as Row;statements.push(env.DB.prepare(`INSERT INTO payment_splits(id,tenant_id,module_id,payment_id,method,amount_cents,external_reference) VALUES(?,?,?,?,?,?,?)`).bind(`${paymentId}:split:${i}`,auth.tenantId,auth.moduleId,paymentId,asText(split.method)??'unknown',toCents(split.amount),asText(split.externalReference)));}statements.push(env.DB.prepare(`INSERT INTO financial_effects(id,tenant_id,module_id,effect_type,reference_type,reference_id,amount_cents,idempotency_key,metadata_json) VALUES(?,?,?,?,?,?,?,?,?)`).bind(randomId('financial_effect'),auth.tenantId,auth.moduleId,'sale_payment','sale',saleId,amount,`${key}:financial`,JSON.stringify({paymentId})));}
    await env.DB.batch(statements);return json({data:await saleDto(env,auth,(await sale(env,auth,saleId))!)},201);
  }
  throw new HttpError(405,'METHOD_NOT_ALLOWED','Method not allowed');
}
