import { requirePermission, type AuthContext } from "../auth";
import { HttpError, json, parseJson, stableJson, type RuntimeEnv } from "../runtime";
import { asText, readBody as body } from "./common";

export async function handleSettings(request: Request, env: RuntimeEnv, auth: AuthContext): Promise<Response> {
  if(request.method==='GET'){requirePermission(auth,'settings:read');const row=await env.DB.prepare(`SELECT * FROM operational_configs WHERE tenant_id=? AND module_id=? LIMIT 1`).bind(auth.tenantId,auth.moduleId).first<Record<string,unknown>>();return json({data:row?{store_name:row.store_name,store_address:row.store_address,store_neighborhood:row.store_neighborhood,store_city:row.store_city,store_phone:row.store_phone,printer_width:String(row.printer_width??80),module_id:auth.moduleId,timezone:row.timezone,autonomy_policy:parseJson(row.autonomy_policy_json,{})}:null});}
  if(request.method==='PATCH'){requirePermission(auth,'settings:write');const x=await body(request);await env.DB.prepare(`INSERT INTO operational_configs(tenant_id,module_id,store_name,store_address,store_neighborhood,store_city,store_phone,timezone,printer_width,max_pdv_discount_basis_points,autonomy_policy_json,metadata_json,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,'{}',CURRENT_TIMESTAMP) ON CONFLICT(tenant_id,module_id) DO UPDATE SET store_name=excluded.store_name,store_address=excluded.store_address,store_neighborhood=excluded.store_neighborhood,store_city=excluded.store_city,store_phone=excluded.store_phone,timezone=excluded.timezone,printer_width=excluded.printer_width,max_pdv_discount_basis_points=excluded.max_pdv_discount_basis_points,autonomy_policy_json=excluded.autonomy_policy_json,updated_at=CURRENT_TIMESTAMP`).bind(auth.tenantId,auth.moduleId,asText(x.store_name),asText(x.store_address),asText(x.store_neighborhood),asText(x.store_city),asText(x.store_phone),asText(x.timezone)??'America/Sao_Paulo',Number(x.printer_width??80)||80,Math.round(Number(x.max_pdv_discount_percent??10)*100),stableJson(x.autonomy_policy??{})).run();return json({data:{ok:true}});}
  throw new HttpError(405,'METHOD_NOT_ALLOWED','Method not allowed');
}
