export const LUNA_CONFIRMATION_RESULTS = Object.freeze({
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  SLOT_BECAME_UNAVAILABLE: 'SLOT_BECAME_UNAVAILABLE',
  COMMERCIAL_CONTRACT_CHANGED: 'COMMERCIAL_CONTRACT_CHANGED',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  COMMIT_RESULT_AMBIGUOUS: 'COMMIT_RESULT_AMBIGUOUS',
  ALREADY_CONFIRMED: 'ALREADY_CONFIRMED',
})

const VALUES = new Set(Object.values(LUNA_CONFIRMATION_RESULTS))

export function isLunaConfirmationResult(value) {
  return VALUES.has(String(value || '').trim())
}
