import { betterAuth } from "better-auth";
import { getMigrations } from "better-auth/db/migration";
import { HttpError, RuntimeEnv, constantTimeTokenMatch, header, parseJson, required } from "./runtime";

export type AuthContext = { userId:string; tenantId:string; moduleId:string; role:string; permissions:string[] };

export function createAuth(env:RuntimeEnv){if(env.BETTER_AUTH_ENABLED!=="true")throw new HttpError(503,"BETTER_AUTH_DISABLED","Better Auth runtime is disabled");return betterAuth({database:env.AUTH_DB,secret:required(env.BETTER_AUTH_SECRET,"BETTER_AUTH_SECRET"),baseURL:required(env.BETTER_AUTH_URL,"BETTER_AUTH_URL"),emailAndPassword:{enabled:true},advanced:{database:{joins:true}}});}
export async function handleAuthRequest(request:Request,env:RuntimeEnv):Promise<Response>{return createAuth(env).handler(request);}

export async function applyAuthMigrations(request:Request,env:RuntimeEnv):Promise<Response>{if(env.APP_ENV!=="staging")throw new HttpError(403,"STAGING_ONLY","Auth migrations are staging-only");if(env.BETTER_AUTH_ENABLED!=="true")throw new HttpError(409,"AUTH_DISABLED","Enable Better Auth before applying schema");const expected=required(env.MIGRATION_TOKEN,"MIGRATION_TOKEN");if(!(await constantTimeTokenMatch(header(request,"x-yuisync-migration-token"),expected)))throw new HttpError(401,"INVALID_MIGRATION_TOKEN","Invalid migration token");const auth=createAuth(env);const migrations=await getMigrations(auth.options);await migrations.runMigrations();return Response.json({ok:true,created:migrations.toBeCreated,added:migrations.toBeAdded},{headers:{"cache-control":"no-store"}});}

export async function linkPendingLegacyIdentities(env:RuntimeEnv,userId:string,email:string):Promise<void>{const pending=await env.DB.prepare(`SELECT legacy_user_id FROM legacy_identity_mappings WHERE legacy_provider='supabase' AND lower(legacy_email)=? AND status='pending_reauthentication'`).bind(email.toLowerCase().trim()).all<{legacy_user_id:string}>();for(const row of pending.results??[]){const legacyPrincipal=`legacy:${row.legacy_user_id}`;await env.DB.batch([env.DB.prepare(`UPDATE legacy_identity_mappings SET auth_user_id=?,status='linked',migrated_at=CURRENT_TIMESTAMP WHERE legacy_provider='supabase' AND legacy_user_id=?`).bind(userId,row.legacy_user_id),env.DB.prepare(`UPDATE tenant_memberships SET user_id=?,updated_at=CURRENT_TIMESTAMP WHERE user_id=?`).bind(userId,legacyPrincipal)]);}}

async function betterAuthIdentity(request:Request,env:RuntimeEnv):Promise<{userId:string;email:string}|null>{if(env.BETTER_AUTH_ENABLED!=="true")return null;const session=await createAuth(env).api.getSession({headers:request.headers});const userId=session?.user?.id,email=session?.user?.email?.toLowerCase().trim();if(!userId||!email)return null;await linkPendingLegacyIdentities(env,userId,email);return{userId,email};}

async function verifiedLegacyIdentity(request:Request,env:RuntimeEnv):Promise<{userId:string;email:string|null}|null>{if(env.LEGACY_IDENTITY_BRIDGE_ENABLED!=="true")return null;const authorization=header(request,"authorization");if(!authorization?.toLowerCase().startsWith("bearer "))return null;const token=authorization.slice(7).trim();if(!token)return null;const base=required(env.SUPABASE_URL,"SUPABASE_URL").replace(/\/$/,"");const serviceRole=required(env.SUPABASE_SERVICE_ROLE_KEY,"SUPABASE_SERVICE_ROLE_KEY");const response=await fetch(`${base}/auth/v1/user`,{headers:{authorization:`Bearer ${token}`,apikey:serviceRole}});if(!response.ok)return null;const legacy=await response.json() as {id?:string;email?:string};if(!legacy.id)return null;const mapped=await env.DB.prepare(`SELECT auth_user_id,status FROM legacy_identity_mappings WHERE legacy_provider='supabase' AND legacy_user_id=? LIMIT 1`).bind(legacy.id).first<{auth_user_id:string|null;status:string}>();if(!mapped)return null;return{userId:mapped.auth_user_id??`legacy:${legacy.id}`,email:legacy.email?.toLowerCase().trim()??null};}

export async function resolveSessionIdentity(request:Request,env:RuntimeEnv):Promise<{userId:string;email:string;name:string|null}>{const session=await betterAuthIdentity(request,env);if(!session)throw new HttpError(401,"AUTH_REQUIRED","Better Auth session required");const better=await createAuth(env).api.getSession({headers:request.headers});return{userId:session.userId,email:session.email,name:better?.user?.name??null};}

export async function resolveAuthContext(request:Request,env:RuntimeEnv):Promise<AuthContext>{const tenantId=header(request,"x-tenant-id"),moduleId=header(request,"x-module-id");if(!tenantId||!moduleId)throw new HttpError(400,"MISSING_SCOPE","x-tenant-id and x-module-id are required");const next=await betterAuthIdentity(request,env);const legacy=next?null:await verifiedLegacyIdentity(request,env);const userId=next?.userId??legacy?.userId??null;if(!userId)throw new HttpError(401,"AUTH_REQUIRED","Authentication required");const membership=await env.DB.prepare(`SELECT role,permissions_json FROM tenant_memberships WHERE user_id=? AND tenant_id=? AND module_id=? AND active=1 LIMIT 1`).bind(userId,tenantId,moduleId).first<{role:string;permissions_json:string}>();if(!membership)throw new HttpError(404,"SCOPE_NOT_FOUND","Resource not found");return{userId,tenantId,moduleId,role:membership.role,permissions:parseJson<string[]>(membership.permissions_json,[])};}

export function requirePermission(context:AuthContext,permission:string):void{if(context.role==="admin"||context.permissions.includes("*")||context.permissions.includes(permission))return;throw new HttpError(403,"FORBIDDEN","Permission denied");}
